baseURL = "https://www.numa-blog.tokyo/"
languageCode = "en-us"
title = "numa's blog ~memo~"
theme = "chunky-poster"
hasCJKLanguage = true
summaryLength = 0
[Params]
  images = ["/static/images/icon-numa.png"]