baseURL = "https://www.numa-blog.tokyo/"
languageCode = "en-us"
title = "numa's blog ~memo~"
theme = "chunky-poster"
hasCJKLanguage = true
summaryLength = 0
[params]
images = ["og.png"]
twitterID = "@__N_u_m_a"
description = "numaの個人ブログです。技術的なことからインターン体験記など投稿しています。"
